# Generated by Django 4.2.14 on 2024-07-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0002_remove_teammember_gender_remove_teammember_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
