# Generated by Django 4.2.14 on 2024-07-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0003_alter_teammember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=True),
        ),
    ]
