# Generated by Django 4.2.14 on 2024-07-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0004_alter_teammember_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
